[package]
name = "bump"
version = "0.1.0"
authors = ["c8h_"]
edition = "2018"

[dependencies]
serde_json = "1"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.reqwest]
version = "0.11"
features = ["blocking", "json"]

